services:
  api:
    build: .
    restart: always
    container_name: api_cash
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy # espera o serviço de database estar funcionando de forma saúdavel
    volumes:
      - api_v:/api
  database:
    image: mysql:8.4
    restart: always
    container_name: mysql_cash
    environment:
      - MYSQL_DATABASE=api_data
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - ./lifecash.sql:/docker-entrypoint-initdb.d/init.sql # usamos a pasta docker-entrypoint-initdb.d para inicializar o db com o dump
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "database",
          "-u",
          "root",
          "-psecret",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  api_v:
